kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: 192.168.56.2
  apiServerPort: 6443
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 32000
    hostPort: 32000
    listenAddress: 192.168.56.2
  - containerPort: 32100
    hostPort: 32100
    listenAddress: 192.168.56.2
  - containerPort: 32200
    hostPort: 32200
    listenAddress: 192.168.56.2
  - containerPort: 32300
    hostPort: 32300
    listenAddress: 192.168.56.2
  - containerPort: 32400
    hostPort: 32400
    listenAddress: 192.168.56.2
  - containerPort: 80
    hostPort: 8080
    protocol: TCP
    listenAddress: 192.168.56.2
  - containerPort: 443
    hostPort: 55443
    protocol: TCP
    listenAddress: 192.168.56.2
# ---
    